min_version = "2026.7.16"

[bootstrap.packages]
"apt:build-essential" = "latest"
"apt:curl" = "latest"
"apt:rcm" = "latest"
"apt:zsh" = "latest"

[bootstrap.repos]
"~/.dotfiles" = { url = "git@github.com:Koronen/dotfiles.git" }

[bootstrap.user]
login_shell = "/usr/bin/zsh"

[dotfiles]
"~/.config/mise/config.toml" = "~/.dotfiles/tag-workstation/config/mise/config.toml"

[settings]
auto_install = false
idiomatic_version_file_enable_tools = ["node", "ruby"]
minimum_release_age = "3d"

[settings.ruby]
default_packages_file = "~/.config/ruby/default-gems"

[tools]
gh = "latest"
node = "lts"
ruby = "latest"
sops = "latest"
usage = "latest"
yamlfmt = "latest"
