min_version = "2026.6.6"

[env]
HK_MISE = 1

[hooks]
postinstall = "hk install --mise"

[tasks.format]
alias = "f"
description = "Format all files"
run = "hk fix --all"

[tasks.lint]
alias = "n"
description = "Lint all files"
run = "hk check --all"

[tasks.pre-commit]
run = "hk run pre-commit"

[tools]
hk = "latest"
pkl = "latest"
yamlfmt = "latest"
