[tasks.format]
alias = "f"
description = "Format all files"
depends = ["format:*"]

[tasks."format:yamlfmt"]
description = "Format YAML files"
run = "yamlfmt ."

[tasks.lint]
alias = "n"
description = "Lint all files"
depends = ["lint:*"]

[tasks."lint:yamllint"]
description = "Lint YAML files"
run = "yamllint ."
wait_for = ["format:yamlfmt"]

[tools]
yamlfmt = "latest"
