---
repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        language: system
        entry: shfmt --write
        types: [shell]
      - id: shfmt-extra
        name: shfmt (extra)
        language: system
        entry: shfmt --write
        files: ^(aliases$|bash_profile$|bashrc$|tag-workstation/zlogin$|zsh/functions/)
        exclude: ^zsh/functions/prompt_koronen_setup$
      - id: shellcheck
        name: shellcheck
        language: system
        entry: shellcheck
        types: [shell]
      - id: shellcheck-extra
        name: shellcheck (extra)
        language: system
        entry: shellcheck
        files: ^(aliases|bash_profile|bashrc|tag-workstation/zlogin|zshenv|zshrc)$
      - id: yamllint
        name: yamllint
        language: system
        entry: yamllint
        types: [yaml]
