#!/usr/bin/env sh

alias ..='cd ..'
alias ack='ack-grep'
alias dbus-suspend='dbus-send --system --print-reply --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend'
alias df='df -h'
alias pag='ps aux | head -n1; ps aux | grep -i'
alias path="echo \$PATH | tr -s ':' '\n'"
if which xdg-open > /dev/null; then
    alias open='xdg-open'
fi
alias trm='rm -f **/*~'

for aliasfile in $HOME/.aliases.d/*.sh; do
    . "$aliasfile"
done

if [ -f "$HOME/.aliases.local" ]; then
    . "$HOME/.aliases.local"
fi
