#!/bin/sh

set -e

if [ -d "$HOME/.tmux" ] && [ ! -d "$HOME/.config/tmux" ]; then
  mkdir -p "$HOME/.config"
  mv "$HOME/.tmux" "$HOME/.config/tmux"
fi

if [ -L "$HOME/.vim" ] && [ -d "$HOME/.dotfiles/vim/pack" ]; then
  rm "$HOME/.vim"
  mkdir "$HOME/.vim"
  mv "$HOME/.dotfiles/vim/pack" "$HOME/.vim/pack"
fi

mkdir -p "$HOME/.vim/pack/plugins/start"

move_plugin() {
  if [ -d "$HOME/.vim/pack/minpac/start/$1" ] && [ ! -d "$HOME/.vim/pack/plugins/start/$1" ]; then
    mv "$HOME/.vim/pack/minpac/start/$1" "$HOME/.vim/pack/plugins/start/$1"
  fi
}

move_plugin "ale"
move_plugin "ctrlp.vim"
move_plugin "editorconfig-vim"
move_plugin "file-line"
move_plugin "vim-colors-solarized"
move_plugin "vim-polyglot"
move_plugin "vim-rspec"

if [ -L "$HOME/.vim/plugin" ]; then
  rm "$HOME/.vim/plugin"
fi
