#!/bin/sh

set -e

if [ -d "$HOME/.tmux" ] && [ ! -d "$HOME/.config/tmux" ]; then
  mkdir -p "$HOME/.config"
  mv "$HOME/.tmux" "$HOME/.config/tmux"
fi

if [ -L "$HOME/.vim" ]; then
  rm "$HOME/.vim"
fi

if [ -L "$HOME/.vim/plugin" ]; then
  rm "$HOME/.vim/plugin"
fi

if [ -L "$HOME/.zsh" ]; then
  rm "$HOME/.zsh"
fi
