---
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  autoFetch: false
  fetchAll: false

gui:
  skipDiscardChangeWarning: true
