#!/bin/sh

set -e

shfmt --case-indent --indent 2 --posix --write \
  .bin/* \
  aliases \
  aliases.d/* \
  bin/* \
  config/shenv.d/* \
  hooks/*/* \
  install.sh \
  profile \
  tag-*/aliases.d/* \
  tag-gpg/bin/* \
  tag-workstation/config/git/templates/hooks/* \
  tag-workstation/zlogin

shfmt --language-dialect bash --indent 4 --write \
  bash/rc.d/* \
  bash_profile \
  bashrc \
  zsh/functions/_kops \
  zsh/functions/_kubectl \
  zsh/rc.d/* \
  zshenv \
  zshrc
