#!/bin/sh

set -e

sudo apt install --yes \
  git \
  rcm \
  shellcheck \
  shfmt \
  yamllint

mkdir -p .git/hooks
printf "#!/bin/sh\n.bin/format && .bin/lint\n" >.git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
