#!/bin/sh

set -e

shellcheck .bin/* \
  bin/* \
  aliases aliases.d/* tag-*/aliases.d/* \
  bash/rc.d/* bash_profile bashrc \
  config/shenv.d/* \
  hooks/**/* \
  install.sh \
  tag-workstation/config/git/templates/hooks/* \
  tag-workstation/zlogin \
  zsh/rc.d/* zshenv zshrc
