#!/bin/sh

set -e

shfmt --case-indent --indent 2 --posix --write \
  .bin/* \
  aliases \
  aliases.d/* \
  bin/* \
  config/shenv.d/* \
  install.sh \
  tag-*/aliases.d/* \
  tag-gpg/bin/* \
  tag-workstation/config/git/templates/hooks/*

shfmt --case-indent --indent 2 --language-dialect auto --write hooks/*/*

shfmt --case-indent --indent 2 --language-dialect bash --write \
  bash/rc.d/* \
  bash_profile \
  bashrc \
  tag-workstation/zlogin \
  zsh/functions/_kubectl \
  zsh/rc.d/* \
  zshenv \
  zshrc
