#!/bin/bash

set -e

(
    cd $(dirname $0)/..
    git submodule init --quiet
    git submodule update --recursive
)

if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
    curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
