#!/usr/bin/env ruby
# frozen_string_literal: true

require 'irb/completion'

IRB.conf[:IRB_NAME] = File.basename(Dir.pwd)
if (env = [ENV['RAILS_ENV'], ENV['RACK_ENV']].compact.first)
  IRB.conf[:IRB_NAME] += "-#{env}"
end

IRB.conf[:SAVE_HISTORY] = 1000

begin
  gem 'awesome_print', '~> 1.1'
  require 'awesome_print'
  AwesomePrint.irb!
rescue Gem::LoadError # rubocop:disable Lint/HandleExceptions
end

local_irbrc_path = '.git/safe/../../.irbrc'
load local_irbrc_path if File.exist?(local_irbrc_path)
