#!/usr/bin/env ruby

begin
  require 'pry-byebug'

  Pry.commands.alias_command 'c', 'continue'
  Pry.commands.alias_command 's', 'step'
  Pry.commands.alias_command 'n', 'next'
  Pry.commands.alias_command 'f', 'finish'
  Pry.commands.alias_command 'b', 'break'
rescue LoadError
  # Ignore
end

Pry.config.prompt_name = File.basename(Dir.pwd)
if env = [ENV['RAILS_ENV'], ENV['RACK_ENV']].compact.first
  Pry.config.prompt_name += "-#{env}"
end
