#!/usr/bin/env sh

set -e

dotdir=`dirname $0`/..
dotdir=$(cd $dotdir && pwd)

# Check for git dependency
if [[ ! which git >/dev/null 2>&1 ]]; then
    if [[ ! sudo apt-get install -y git >/dev/null 2>&1 ]]; then
        echo "[-] Missing dependency: git" >&2
        exit 1
    fi
fi

# Clone prezto
test -d "${ZDOTDIR:-$HOME}/.zprezto" || git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# Clone fasd
test -d "$HOME/.fasd" || git clone https://github.com/clvv/fasd.git "$HOME/.fasd"

# Symlink files
dotfiles="ackrc bash_profile bashrc dircolors gemrc gitattributes gitconfig gitignore i3/config inputrc irbrc profile screenrc tmux.conf vimrc zshenv zlogin zlogout zpreztorc zshrc"
for dotfile in $dotfiles; do
    ln -sf "$dotdir/$dotfile" "$HOME/.$dotfile"
done
unset dotfiles

unset dotdir
