#!/bin/bash

set -e

# Clone prezto
test -d "${ZDOTDIR:-$HOME}/.zprezto" || git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# Check for fasd dependency
if ! which fasd >/dev/null 2>&1; then
    echo "[-] Missing dependency: fasd" >&2
    echo "[-] See https://github.com/clvv/fasd for installation instructions." >&2
fi

git submodule update --init
