#!/usr/bin/env sh

set -e

if command -v docker-compose > /dev/null; then
    curl -Ls "https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/zsh/_docker-compose" > ~/.zsh/functions/_docker-compose
fi
