#!/usr/bin/env sh

set -e

mkdir -p "$HOME/.vim/pack/minpac/opt"

if [ ! -d "$HOME/.vim/pack/minpac/opt/minpac" ]; then
    git clone https://github.com/k-takata/minpac.git \
        "$HOME/.vim/pack/minpac/opt/minpac"
fi
