#!/bin/sh

set -e

remove_old_symlink() {
  if [ -L "$1" ] && [ ! -e "$1" ]; then
    rm "$1"
  fi
}

remove_old_symlink "$HOME/.dircolors"
remove_old_symlink "$HOME/.gemrc"
remove_old_symlink "$HOME/.gitattributes"
remove_old_symlink "$HOME/.gitconfig"
remove_old_symlink "$HOME/.gitconfig.local"
remove_old_symlink "$HOME/.gitignore"
remove_old_symlink "$HOME/.gittemplate"
remove_old_symlink "$HOME/.irbrc"
remove_old_symlink "$HOME/.pryrc"
remove_old_symlink "$HOME/.railsrc"
remove_old_symlink "$HOME/.rspec"
remove_old_symlink "$HOME/.rubocop.yml"
remove_old_symlink "$HOME/.tmux.conf"
