#!/bin/sh

set -e

if [ ! -f "$HOME/.config/tmux/tmuxcolors-256.conf" ]; then
  ref=4d07f3cc1ce2bdc0c8391290c5b0cf098abddddc
  curl -sSo "$HOME/.config/tmux/tmuxcolors-256.conf" \
    "https://raw.githubusercontent.com/seebi/tmux-colors-solarized/$ref/tmuxcolors-256.conf"
fi
