#!/bin/sh

set -e

PACKS_PATH="$HOME/.vim/pack"

mkdir -p "$PACKS_PATH"

pack() {
  url="$1"
  ref="$2"
  plugin_path="${PACKS_PATH}/$3"

  if [ ! -d "$plugin_path" ]; then
    git clone "$url" "$plugin_path"
  else
    git -C "$plugin_path" fetch --quiet
  fi

  git -C "$plugin_path" checkout --quiet "$ref"
}

pack "https://github.com/altercation/vim-colors-solarized.git" "528a59f26d12278698bb946f8fb82a63711eec21" "plugins/start/vim-colors-solarized"
pack "https://github.com/ctrlpvim/ctrlp.vim.git" "3739dcd638f457559d5a1ae1e398276175694e4b" "plugins/start/ctrlp.vim"
pack "https://github.com/editorconfig/editorconfig-vim.git" "c0227885a06b155d5aa5465e08b9800e8c939f70" "plugins/start/editorconfig-vim"
pack "https://github.com/k-takata/minpac.git" "7a616ad2393139dbdf7514c14606098404e38625" "minpac/opt/minpac"

if [ -L "$HOME/.vim/spell/Makefile" ]; then
  pack "https://github.com/dense-analysis/ale.git" "178fe113564d31cba304263765aeb21e7ed23a7e" "plugins/start/ale"
  pack "https://github.com/thoughtbot/vim-rspec.git" "c0251b2e40eba5c9fb145adb8896424fa11972da" "plugins/start/vim-rspec"
  pack "https://github.com/sheerun/vim-polyglot.git" "f061eddb7cdcc614c8406847b2bfb53099832a4e" "plugins/start/vim-polyglot"
fi
