#!/bin/sh

set -e

PACKS_PATH="$HOME/.vim/pack"

mkdir -p "$PACKS_PATH"

pack() {
  url="$1"
  ref="$2"
  plugin_path="${PACKS_PATH}/$3"

  if [ ! -d "$plugin_path" ]; then
    git clone "$url" "$plugin_path"
  else
    git -C "$plugin_path" fetch --quiet
  fi

  git -C "$plugin_path" checkout --quiet "$ref"
}

pack "https://github.com/k-takata/minpac.git" "7a616ad2393139dbdf7514c14606098404e38625" "minpac/opt/minpac"
